KP-890 [Git] Requires password when an SSH key is given
Kaholo/kaholo-plugin-git pull request #22
Opened 2022-08-25 08:21 UTC by xkcm

[**KP-890 in Jira**](https://kaholo.atlassian.net/browse/KP-890)

2022-08-25 10:12 UTC, graddaniel requested changes

2022-08-25 10:12 UTC, graddaniel commented on helpers.js
> +        resolvedStdout = `${stderr}\nSuccess!`;
If there's no output and the command returns an error, then it's a success?

2022-08-25 10:30 UTC, xkcm commented on helpers.js
> +        resolvedStdout = `${stderr}\nSuccess!`;
It didn't make sense to me too, I'll change that

2022-08-26 11:36 UTC, graddaniel approved these changes

2022-08-26 17:06 UTC, merged